apiVersion: core.oci.jet.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: instance-via-crossplane5
spec:
  forProvider:
    compartmentIdRef: 
      name : compartment-via-crossplane5
    createVnicDetails:
      - subnetIdRef: 
          name : subnet-via-crossplane5
    availabilityDomain: "hrtP:US-ASHBURN-AD-2"
    shape: "VM.Standard.E2.1.Micro"
    sourceDetails:
      - sourceId: ocid1.image.oc1.iad.aaaaaaaanpammf3j2xcbcoykbwlk3m35ko6svsdj2sut2fjtmnmujcnh3pvq
        sourceType: "image"